### ISSUE TITLE
Real time communication / Web socket

### ISSUE THREAD

**Issue by brillout** [reframejs/wildcard-api#10]
Myself and @lostpebble have been discussing adding two way communication to Wildcard in #3.

**Comment by brillout** [comment]
@lostpebble

> The only thing that might be confusing is having both of those things on the endpoints namespace.

Ok yea you're right. Maybe we could rename `endpoints` to `server`. And then add a new object called `clients`.

**Comment by brillout** [comment]
From the client perspective, it makes sense to have `server.aFunctionDefinedInTheServer();`. Maybe more than `server.aFunctionDefinedInTheServer();`.

**Comment by lostpebble** [comment]
@brillout yea I like that naming better - its more deliberate and readable. Could maybe do with a little extra to be more obvious too (such as `serverEndpoints` and `clientEndpoints`), but I know you would prefer to keep it as short as possible.

**Comment by brillout** [comment]
:+1:

**Comment by brillout** [comment]
I have some ideas about this. I believe we can pull this off in a neat way. If anyone is interested in this, please ping me here.

**Comment by johnson544** [comment]
Hi @brillout, did you continue with web socket support ?  I am interested to try it out. Thx!

**Comment by brillout** [comment]
Hi @johnson544 :-)

No one needed bi-directional communication so far but I'd be up to implement that! Should be fun.

What's your use case?

**Comment by johnson544** [comment]
Hi @brillout, I played around with a Trello clone in GraphQL using subscriptions. I feel it was way too much boilerplate for a simple CRUD actions and reordering of cards.

I feel something like graphql's  @defer and @stream option would be really cool.  

Also I can think of a realtime endpoint that automatically watches for changes and appends, updates, or removes elements based on conditions. The condition handlers could be setup same as ORM's handle relations in its models. 

I am also based in Germany. If you want to chat more about it we can schedule a call :-)

a side node: What I really like in graphql is fetching certain fields from a type. I feel a helper function that deals with pagination and over-fetching would be also very cool. something like https://github.com/spatie/laravel-query-builder

**Comment by brillout** [comment]
Hallo @johnson544,

(cc @lostpebble)

Okay so my idea for realtime bi-directional communication is to extend Wildcard to allow "passing" callback functions as arguments.

~~~js
// Browser

const {endpoints} = require('@wildcard-api/client');

const {_connection} = endpoints.onHello(message => {
  console.log('Hello '+message+' !');
});

_connection.onClose(() => {
  // The connection to the server has been closed (or lost).
});

_connection.close();
assert(_connection.isClosed===true);
~~~

~~~js
// Node.js server

const {endpoints} = require('@wildcard-api/server');

endpoints.onHello = async function(callback) {
  callback('@johnson544');
  await sleep(1);
  callback('@lostpebble');
};

function sleep(seconds) {
  return new Promise(resolve => setTimeout(resolve, seconds*1000));
}
~~~

The browser then prints:

~~~js
'Hello @johnson544 !'
// And after 1 second:
'Hello @lostpebble !'
~~~

I call this feature *callback arguments*.

With callback arguments, your Trello clone would do something like this:

~~~js
// Browser

const {endpoints} = require('@wildcard-api/client');

const cardsStore = {};

endpoints.onTrelloCardsChange(function(cards){
  cards.forEach(card => {
    cardsStore[card.id] = card;
  });

  renderWithReact(cardsStore);
});
~~~

~~~js
// Node.js server

const {endpoints} = require('@wildcard-api/server');

endpoints.onTrelloCardsChange = function(callback) {
  rethinkdb
  .table('cards')
  // only return cards that the user has permission to read
  .filter({authorizedUserIds: this.user.id})
  .changes()
  .run(function(cards, databaseConnection) {
    // Wildcard sets `callback` to `null` when the browser connection is closed
    if( callback===null ) {
      databaseConnection.close();
    } else {
      // The `callback` function defined in the browser is called
      // every time there is a change in the cards list.
      callback(cards);
    }
  });
};
~~~

### `@defer` & `@stream`

Today, something like `@defer` can be done with Wildcard by doing:

~~~js
// Browser

const {endpoints} = require('@wildcard-api/client');

const highPrioData = await endpoints.getHighPrioData();

// We defer heavy and non-important data

const lowPrioData = await endpoints.getLowPrioData();
~~~

With callback arguments you'd be able to implement streaming and further defer optimizations:

~~~js
// Browser

const {endpoints} = require('@wildcard-api/client');

const newsItemsStore = {};

// Streaming:
// (Can also be used to defer)

endpoints.getNewsItems(function(newsItems){
  newsItems.forEach(item => {
    newsItemsStore[item.id] = item;
  });

  renderWithReact(newsItemsStore);
});
~~~

The goal with callback arguments is to provide bi-directional communication in a simple, powerful, and JavaScript-idiomatic way.

What do you think?

@lostpebble: I'm curious, what do you think?

> I am also based in Germany. If you want to chat more about it we can schedule a call :-)

Gerne :-) Write me on Twitter (https://twitter.com/brillout) or email me (github@brillout.com) and I'll give you my WhatsApp number.

> a side node: What I really like in graphql is fetching certain fields from a type. I feel a helper function that deals with pagination and over-fetching would be also very cool. something like https://github.com/spatie/laravel-query-builder

The idea with Wildcard is to directly use SQL/ORM queries; with Wildcard, you can simply use the pagination tools of your database.

There is no over-fetching problem with Wildcard as you can write your enpdoint functions to return only and exactly what your frontend needs. For example:

~~~js
// Node.js server

const {endpoints} = require('@wildcard-api/server');

const Todo = require('./path/to/your/data/model/Todo');

// Get all (and only the needed) data for the landing page.
endpoints.getLandingPageData = async function() {
  const todos = await (
    Todo
    .select(['id', 'text'])
    .find({userId: this.user.id, completed: false})
  );

  return {
    user: {
      name: this.user.name,
    },
    todos,
  };
};
~~~

**Comment by brillout** [comment]
And please feel free to be very critical. I'm more than happy to hear very negative feedback and completely different approaches.

How would *you* design bi-directional communication with Wildcard?

**Comment by brillout** [comment]
cc @johnson544, @lostpebble 

Okay so my idea for realtime bi-directional communication is to extend Wildcard to allow "passing" callback functions as arguments.

~~~js
// Browser

const {endpoints, connection} = require('@wildcard-api/client');

endpoints.onHello(callback);

// The callback defined in the browser is "called" by our Node.js server.
function callback(message) {
  console.log('Hello '+message+' !');
}

connection.onClose(() => {
  // The connection to the server has been closed (or lost).
});

connection.close();
assert(connection.isClosed===true);
~~~

~~~js
// Node.js server

const {endpoints} = require('@wildcard-api/server');

endpoints.onHello = async function(callback) {
  // We call the callback defined in the browser from within Node.js
  callback('@johnson544');
  await sleep(1);
  callback('@lostpebble');
};

function sleep(seconds) {
  return new Promise(resolve => setTimeout(resolve, seconds*1000));
}
~~~

The browser then prints:

~~~js
'Hello @johnson544 !'
// And after 1 second:
'Hello @lostpebble !'
~~~

I call this feature *callback arguments*.

With callback arguments, your Trello clone could do something like this:

~~~js
// Browser

const {endpoints} = require('@wildcard-api/client');

const cardsStore = {};

endpoints.onTrelloCardsChange(function(cards) {
  cards.forEach(card => {
    cardsStore[card.id] = card;
  });

  renderWithReact(cardsStore);
});
~~~

~~~js
// Node.js server

const {endpoints} = require('@wildcard-api/server');

endpoints.onTrelloCardsChange = function(callback) {
  // Real-time Database with e.g. RethinkDB
  rethinkdb
  .table('cards')
  // only return cards that the user has permission to read
  .filter({authorizedUserIds: this.user.id})
  // Listen for changes
  .changes()
  .run(function(cards, databaseConnection) {
    // Wildcard sets `callback.isClosed` to `true`
    // when the browser connection is closed/lost
    if( callback.isClosed ) {
      databaseConnection.close();
    } else {
      // The `callback` function defined in the browser is called
      // every time there is a change in the cards list.
      callback(cards);
    }
  });
};
~~~

**Comment by johnson544** [comment]
Cool, I can see callbacks perfectly working for defer. Really like it!

But how would it work with web sockets like socket.io ? So that new cards are broadcasted to all sessions?

For my Trello example I created below subscription for creating cards:

```
  Mutation: {
    createCard: authenticated(async (_, { input }, ctx) => {
      const card = await ctx.db(TABLE).create(input)
      ctx.pubsub.publish("cartCreated", { cartCreated: card })
      return card
    })
  },
  Subscription: {
    cartCreated: {
      subscribe: withFilter(
        (_, __, { pubsub }) => pubsub.asyncIterator("cartCreated"),
        async (payload, variables) => variables.boardId == payload.cartCreated.boardId
      )
    }
  }
}
```

**Comment by lostpebble** [comment]
Looks pretty cool so far @brillout . Sorry, I've been busy lately so haven't had time to really dig into it and think about it properly.

Just one thing that stands out to me at the moment is that it seems like this API is happening on the same objects as the current REST API stuff?

```ts
const {endpoints} = require('@wildcard-api/client');
```

My main concern would be this clashing with the current API, as currently it works completely differently (no room for `callback` as shown here, because we just send function arguments directly). So I would hope that this is on some kind of different wildcard endpoint altogether so its easier to separate the concepts.

Otherwise, I'll try take a closer look at everything soon and let you know my thoughts :)

**Comment by brillout** [comment]
@johnson544 I've given the callback arguments idea more thoughts and unfortunately the usability of callback arguments becomes complex around edge cases.

@lostpebble Yes I like the minimalism of the idea :-) but unfortunately the UX is less than ideal around edge cases. Thanks for chiming in and no worries about not replying :-)

I'll give real communication with Wildcard more thoughts and write down my conclusions here. Stay tuned :-).

**Comment by brillout** [comment]
Got a new idea, I'll let you know about it today / the next couple of days.

**Comment by brillout** [comment]
(I'm not forgetting about this:))

**Comment by brillout** [comment]
The new design is almost complete, I only have to flesh out couple of details.

**Comment by johnson544** [comment]
I am excited about it!!

 I just replaced all graphql subscriptions with socket.io because it annoyed me too much. I feel they haven't really thought them through.

Whatever you come up with,  please also consider connecting / disconnecting listeners for channels on the server. It's so helpful to clean up sessions:

```
io.on('connection', function(socket){
    console.log('a user connected: ' + socket.id);
    socket.on('disconnect', function(){
        console.log( socket.name + ' has disconnected from the chat.' + socket.id);
    });
    socket.on('join', function (name) {
        socket.name = name;
        console.log(socket.name + ' joined the chat.');
    });
});
```

**Comment by brillout** [comment]
Designing error handling to be simple for server->client communication turns out to be difficult.

But I'm making progress :-).

Stay tuned! :)

**Comment by brillout** [comment]
>  please also consider connecting / disconnecting listeners

I am ;-)

**Comment by brillout** [comment]
I've lowered the prio of this. But I'm still very much interested in implement this. If someone reading this needs it for a production app then let me know and I'll implement this.

**Comment by brillout** [comment]
Closing in favor of https://github.com/reframejs/wildcard-api/issues/61.

It's a design based on the callbacks idea described here, but with the addition of two `_onClose` lifecycle functions which should allow for simple lifecycle management.
