### ISSUE TITLE
Hanging requests (in browser) with invalid payloads.

### ISSUE THREAD

**Issue by sustained** [reframejs/wildcard-api#13]
Cool little project!

----

Create a basic endpoint e.g. mine is:

```js
endpoints.hello = function(payload) {
  return {
    message: `Welcome ${payload.name}!`
  };
};
```

So, if you visit `/wildcard/hello` in the browser then you'll get a `500` + a stack trace etc. printed, seems good so far.

If you visit e.g. `/wildcard/hello/%5B%7B%22name%22%3A%22Alice%22%7D%5D` then you get a `200` + the API response, also seems good (although I don't understand why the object is within an array in the URL?

However if you visit e.g. `/wildcard/hello/foo` then the request hangs indefinitely, as far as I can tell and you get this error server-side:

```
ReferenceError: endpointArgsString is not defined
    at parseRequest (.../wildcard-test/node_modules/wildcard-api/server/WildcardApi.js:136:36)
    at getApiResponse (.../wildcard-test/node_modules/wildcard-api/server/WildcardApi.js:53:71)
```

Maybe this isn't really a bug but you would expect it to not hang indefinitely, that seems bad?

Note that I'm using this with Express.

**Comment by brillout** [comment]
> Cool little project!

Thanks!

> So, if you visit /wildcard/hello in the browser then you'll get a 500 + a stack trace etc. printed, seems good so far.

Yes that's expected because your endpoint function will throws an error when trying access `payload.name` while `payload` is `undefined`.

> why the object is within an array in the URL?

Because it's the **list** of arguments, thus an array.
Imagine you'd call `endpoints.hello('firstArg', 'secondArg')`.

> request hangs indefinitely,

I just published a new version `wildcard@0.5.1` that returns a `404` instead of a `500` when calling a malformatted URL such as `/wildcard/hello/foo`. Your request won't hang indefinitely anymore.

**Comment by sustained** [comment]
Excellent, thanks for the prompt response and fix.

But I think a 422 or even a 400 would be more appropriate.

```The 422 (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a 415 (Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions.```

```The 400 (Bad Request) status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).```

Probably a 400, as it's the *syntax* of the URL that is incorrect.

**Comment by brillout** [comment]
You're right, `400` is better than `404` here.

Done and `wildcard@0.5.2` now returns `400`.

Thanks for opening the issue & let me know if you run into any problem.

**Comment by sustained** [comment]
:tada:

**Comment by brillout** [comment]
I'm going to change all status code to `500` for any failed request. With Wildcard, you shouldn't care about all the HTTP stuff, instead Wildcard should print an error with what went wrong and how to solve the problem.

Let me know if that poses any problem for you.
