### ISSUE TITLE
How to know if running in Node.js internal or client request context

### ISSUE THREAD

**Issue by lostpebble** [reframejs/wildcard-api#14]
I've noticed that you're using a `Proxy` for `this` inside of endpoint functions when we're running directly in Node.js (outside of a request context). This is making it a bit difficult for me to run checks on which context we're actually on because any property access on `this` now throws an error (I understand why you set it up this way, as it helps beginners). Maybe it could be best if there was a way we could disable the proxy?

Currently I've resolved my issue by doing this:

```ts
import util from "util";

// inside the endpoint code
if (!util.types.isProxy(this)) {
  // running on Node internal SRR
} else {
  // running on Node client-request context
}
```

It works, but it feels a bit messy and undetermined (I never know when you might decide that you'd like to change the value of `this` in the future).

Do you have any ideas? All I'd like is a way for me to know that I'm in a request context or not. I'm using this to try help solve the awkwardness of using authentication while SSR.

**Comment by lostpebble** [comment]
The original way I tried to solve it:

```ts
// in request route
const requestProps = {
      url: ctx.url,
      method: ctx.method,
      body: ctx.request.body,
      session: ctx.session,
      isClientRequest: true,
 };

const { body, statusCode, contentType } = await wildcard.getApiResponse(requestProps);
```

And then I was checking `this.isClientRequest` - but of course, that throws the error from the `Proxy` you've set up for non-request contexts when my app is SSR.

**Comment by brillout** [comment]
You could:

~~~js
// Browser + Node.js

const {endpoints} = require('wildcard-api/client');

module.export = async function() {
  const {paulEndpoint} = endpoints;

  if( isNodejs() ) {
    paulEndpoint = paulEndpoint.bind({isClientRequest: false});
  }

  await paulEndpoint();
};

// Whether the code runs in the browser or in Node.js
function isNodejs() {
  return typeof window === "undefined";
}
~~~

`isClientRequest` is now always available:

~~~js
// Node.js

const {endpoints} = require('wildcard-api');

endpoints.paulEndpoint = async function() {
  if( this.isClientRequest===false ) {
    // Comes from Node.js
  } else {
    // Comes from Browser
  }
};
~~~

> I'm using this to try help solve the awkwardness of using authentication while SSR.

The idiomatic way to do auth with Wildcard is:

~~~js
// Browser + Node.js

const {endpoints} = require('wildcard-api/client');

// `ctx` comes from your Koa route
module.export = async function(ctx) {
  const {paulEndpoint} = endpoints;

  if( isNodejs() ) {
    const {headers} = ctx.request;
    paulEndpoint = paulEndpoint.bind({headers});
  }

  await paulEndpoint();
}

// Whether the code runs in the browser or in Node.js
function isNodejs() {
  return typeof window === "undefined";
}
~~~

Thanks to `bind`, the endpoint function `paulEndpoint` has always access to the headers:

~~~js
// Node.js

const {endpoints} = require('wildcard-api');
const getUser = require('./path/to/your/auth/getUser');

endpoints.paulEndpoint = async function() {
  const user = await getUser(this.headers);

  /* ... */
};
~~~

Would this be a solution for you?

PS: I'm going to re-write the `SSR & Authentication` docs. I'm currently doing a poor job at explain what's going on.

PS2: Btw., I'm still planing to popularize Wildcard which I will do soon (hopefully in the coming weeks/months).

**Comment by lostpebble** [comment]
I see, I'm actually already passing some things down differently to make the endpoint run differently if its coming from a request context or being run internally on Node.js. I'm not using `bind()` though - I'm just augmenting my arguments passed to the endpoint (same end result really).

But for security reasons (I have different methods for authentication depending on which context we're in), I don't want the client to ever be able to send false information that makes the endpoint think that we're on the internal Node.js context instead of the request context- for this reason I need to be able to check this, outside of what can be put in `.bind()` or passed into the endpoint function (as I'm doing now).

If we're on the Node.js internal context I check the augmented values which I've set to pass into my function only when doing SSR. If we're not - I check the request's session for user auth information.

**Comment by brillout** [comment]
> I'm actually already passing some things down differently to make the endpoint run differently if its coming from a request context or being run internally on Node.js.
> But for security reasons (I have different methods for authentication depending on which context we're in)

Why is your endpoint behaving differently depending whether it's called from the browser or from Node.js?

The idea of SSR is to have the exact same view rendered to HTML then again to the DOM.
I'm not sure why you would want to have a different logic resulting into the same view.

> I don't want the client to ever be able to send false information

Yes, the endpoint arguments are not safe. Anyone can pass any arbitrary data as arguments.

This is not the case with `bind()`. The ability to `bind()` is only available to Node.js and is therefore safe. Any data in the `this` object of your endpoint functions originates from *your* code in Node.js.

The `this` object is either;
- The object you pass to `getApiResponse`
- The object you pass to `bind()`

The `this` object is always an object *you* determined.

> If we're on the Node.js internal context I check the augmented values which I've set to pass into my function only when doing SSR. If we're not - I check the request's session for user auth information.

It really sounds like you should go with the idiomatic Wildcard way, that is to pass these augmented values to your endpoint function by using `.bind()`.

Thanks for opening this ticket and making me aware that the documentation can be improved. I've started to re-write the whole SSR+auth section.

> P.S. Looking forward to Wildcard getting more popular! Still surprised it's not, as it really is a nice library.

Thanks. Btw, we are both in the current Startup School track. Do you sometimes participate in your Vibescout's group session? If yes then I could try to arrange that we both end up in the same group session on Thursday. It could be fun to see my first Wildcard user!

**Comment by lostpebble** [comment]
> Why is your endpoint behaving differently depending whether it's called from the browser or from 
> Node.js?
>
>The idea of SSR is to have the exact same view rendered to HTML then again to the DOM.
> I'm not sure why you would want to have a different logic resulting into the same view.

The logic is exactly the same. Its simply because of the way that I'm using Wildcard in conjunction with my library Pullstate. My Wildcard API is being called from inside my React render cycle which makes it impossible for me to pass `ctx` to it - but I have other ways of passing state through my state stores in my app (I've developed an Async-state handler for React on top of which I run Wildcard).

On Node.js I set a special value in those stores when the request starts, and this is what allows authentication internally while SSR.

Basically I wrap all my async functions like this:

```ts
function wrapAuthenticatedTaskFunctionEndpoint<A = any>(endpoint: (args: A) => Promise<ITaskFunctionResponse>, name: string = "") {
  return async (args, { UserStore }) => {
    if (name.length > 0) {
      console.log(`Running (authed) async action "${name}"`);
    }

    const jwt = UserStore.getRawState().jwt;

    if (jwt) {
      args.__at = jwt;
    }
    const response = await endpoint(args);
    return response.positive
      ? successResult(response.payload)
      : errorResult(response.endTags, response.endMessage);
  };
}
```

So `jwt` is a JSON web token I set in my stores. Which I then augment the arguments passed to my Wildcard endpoint, using `__at` (access token), which I then check for inside the endpoint, or otherwise use `ctx.session` (because we have access to it now during a request context) to validate the user.

> This is not the case with bind(). The ability to bind() is only available to Node.js and is therefore safe. Any data in the this object of your endpoint functions originates from your code in Node.js.

Ah okay, fair enough - I think I could solve my issue using that then. It makes sense... completely overlooked the fact that `bind` isn't serializable over the wire 🤦‍♂ haha

Gonna see if I can solve everything using the idiomatic way now. Thanks for pointing me in the right direction!

> Thanks. Btw, we are both in the current Startup School track. Do you sometimes participate in your Vibescout's group session? If yes then I could try to arrange that we both end up in the same group session on Thursday. It could be fun to see my first Wildcard user!

Oh that's really cool! Unfortunately on Thursday I'm busy travelling across country and might not have much internet access. To be honest I haven't been very involved personally with the Startup School stuff, my brother (and business partner) is taking on that side of things while I try finish off a lot of dev backlogs. But if there are more sessions later, I'd definitely be keen to try join you at one!

**Comment by brillout** [comment]
Ok I see.

So yea, you could do this:

~~~js
function wrapAuthenticatedTaskFunctionEndpoint<A = any>(endpoint: (args: A) => Promise<ITaskFunctionResponse>, name: string = "") {
  return async (args, { UserStore }) => {
    if (name.length > 0) {
      console.log(`Running (authed) async action "${name}"`);
    }

    const jwt = UserStore.getRawState().jwt;

    if (jwt) {
      endpoint = endpoint.bind({jwt});
    }
    const response = await endpoint(args);
    return response.positive
      ? successResult(response.payload)
      : errorResult(response.endTags, response.endMessage);
  };
}
~~~

Then in your endpoint function:

~~~js
const {endpoints} = require('wildcard-api');

endpoints.paulEndpoint = async function(args) {
  if( this.jwt ){
    // Server-side Auth
  } else {
    // Client-side Auth
  }

  /* ... */
};
~~~

> But if there are more sessions later, I'd definitely be keen to try join you at one!

Ok I'll let you know if I manage to arrange a group session with Vibescout! (Normally the group session participants are randomly shuffled together.)

I've looked into Pullsate &mdash; super interesting. I find the whole state management topic fascinating. I feel like state management is going to be very very different in 10 years than what we do today.

**Comment by brillout** [comment]
Also I've finished re-writing the SSR+Auth docs. On a high level, it should be much clearer. I still need to polish some low level stuff though.

**Comment by lostpebble** [comment]
> So yea, you could do this:

I've actually done it **exactly** like that. haha. Working perfect.

> I've looked into Pullsate — super interesting. I find the whole state management topic fascinating. I feel like state management is going to be very very different in 10 years than what we do today.

Cool. Yea state management is interesting. I didn't like most what was out there, so made my own (based off an abandoned library which I enjoyed). I just want whatever is the most simple way to change object "stores" and have the UI react accordingly - most other libraries are very verbose in this. I've extended it with some interesting extras too, like async state handling and lots of things surrounding that - check out the section on [async hooks](https://lostpebble.github.io/pullstate/docs/async-hooks-overview) to get an idea how I'm solving it if you'd like. Allows for handling many edge cases quite easily.

I'm still gonna put together a video soon to try help promote it soon.

> Also I've finished re-writing the SSR+Auth docs. On a high level, it should be much clearer. I still need to polish some low level stuff though.

Cool, I'll take a look.

**Comment by lostpebble** [comment]
Seeing as my situation has been solved by using `bind()`, I think we can close this.

**Comment by brillout** [comment]
> I've actually done it exactly like that. haha. Working perfect.

Hehe :D

> most other libraries are very verbose in this

Same here &mdash; I'm not super happy with how state management is currently being done.

> check out the section on async hooks to get an idea how I'm solving it

Ok makes sense from a data fetching perspective. One thing I was thinking while reading about it is: "this is very tailored towards data fetching, could it be extracted outside of Pullstate's core?". I.e. maybe it could be library that uses Pullstate instead of being part of Pullstate. Would super neat if Pullstate has a super simple core with a minimal interface that I can learn within 10mn. Then bunch of libraries could be built on top of it, such as async data fetching.

> I've looked into Pullsate — super interesting

I dig Pullstate's readme; it makes me want to use Pullstate. I really the idea of having a multitude of global immutable states that are easy to update and that I can use anywhere in my React tree. That's super neat. Seems to be much easier than Redux. I'll give Pullstate a try in my next React project.

> I didn't like most what was out there, so made my own

Did the same two years ago :) https://github.com/brillout/reprop but don't bother reading it, I've stopped developing it.


I may re-work on state management at some point in the future. I'd then start anew and from first principles. I'll then see how much I converge or diverge with Pullstate and let you know.

**Comment by lostpebble** [comment]
> "this is very tailored towards data fetching, could it be extracted outside of Pullstate's core?"

That is true, there is a bit of code there that could be extracted outside of Pullstate's core - but at the same time, there is a lot which is tightly integrated with Pullstate too - such as being able to integrate your stores into asynchronous actions at every step of the way in a SSR capable way (and in the hooks etc.).

At the moment the library doesn't really weigh in very high. For the amount of code you save writing out async logic, an extra couple KBs in the library isn't gonna hurt.

I am however thinking of abstracting out some things, such as state helpers for undo / redo functionality and other optional tools which can make your journey with state a lot easier.

> Would super neat if Pullstate has a super simple core with a minimal interface that I can learn within 10mn

The core of Pullstate is super simple and you should be up and running after going through the first example. The asynchronous stuff is completely optional, but generally a very common next step when dealing with state in your app- hence its inclusion.

> I'll give Pullstate a try in my next React project.

Great! :) Looking forward to hearing what you think of it.

> I may re-work on state management at some point in the future. I'd then start anew and from first principles. I'll then see how much I converge or diverge with Pullstate and let you know.

Cool. Everyone seems to have a different opinion about state management haha! The issue being that there are so many "competitors" in that area now. I'd be interested to see what you come up with though!

**Comment by brillout** [comment]
@lostpebble Ok makes sense
