### ISSUE TITLE
`Cannot convert a Symbol value to a string` when `console.log()`ing `this` in endpoint function

### ISSUE THREAD

**Issue by chriscalo** [reframejs/wildcard-api#16]
The getting started section of the [Wildcard API docs][wildcard-docs] state that `this` will be equal to the `requestProps` object passed to `getApiResponse()`.

``` js
// Node.js

const {endpoints} = require('wildcard-api');

endpoints.myFirstEndpoint = async function () {
  // The `this` object is the `requestProps` object we passed to `getApiResponse`. Because
  // the headers are set on `requestProps.headers`, we can access them over `this.headers`.
  // You can then, for example, use the headers for authentication.
  console.log('The HTTP request headers:', this.headers);

  return {msg: 'hello from my first Wildcard endpoint';
};
```

I tried `console.log()`ing `this` from an endpoint function:

``` js
import { endpoints } from "wildcard-api";
import { file } from "ez-file";

endpoints.greet = async function greet() {
  // The getting started section of the [Wildcard API docs][wildcard-docs] state
  // that `this` will be equal to the `requestProps` object passed to
  // `getApiResponse()`.
  //
  // [wildcard-docs]: https://github.com/reframejs/wildcard-api
  console.log(this);
  return await file("./greeting.txt");
};
```

Unfortunately, it blows up with the following error:

``` text
TypeError: Cannot convert a Symbol value to a string
    at RegExp.test (<anonymous>)
    at getPropString (/Users/ccalo/Projects/goldpage-vue-express-starter/node_modules/wildcard-api/server/WildcardApi.js:687:23)
    at Object.get (/Users/ccalo/Projects/goldpage-vue-express-starter/node_modules/wildcard-api/server/WildcardApi.js:673:28)
    at Proxy.toString (<anonymous>)
    at /Users/ccalo/Projects/goldpage-vue-express-starter/node_modules/esm/esm.js:1:163189
    at /Users/ccalo/Projects/goldpage-vue-express-starter/node_modules/esm/esm.js:1:188786
    at Object._s (/Users/ccalo/Projects/goldpage-vue-express-starter/node_modules/esm/esm.js:1:197621)

    at Object.<anonymous> (/Users/ccalo/Projects/goldpage-vue-express-starter/node_modules/esm/esm.js:1:199489)
    at Object.apply (/Users/ccalo/Projects/goldpage-vue-express-starter/node_modules/esm/esm.js:1:199279)
    at Object.[nodejs.util.inspect.custom] (/Users/ccalo/Projects/goldpage-vue-express-starter/node_modules/esm/esm.js:1:203874)
    at formatValue (internal/util/inspect.js:491:31)
    at inspect (internal/util/inspect.js:189:10)
    at Object.formatWithOptions (util.js:84:12)
    at Object.Console.(anonymous function) (console.js:191:15)
    at Object.log (console.js:202:31)
    at Object.ha (/Users/ccalo/Projects/goldpage-vue-express-starter/node_modules/esm/esm.js:1:203749)
```

See the [bug-when-logging-this-in-endpoint-function][] branch to reproduce this error.

[wildcard-docs]: https://github.com/reframejs/wildcard-api
[bug-when-logging-this-in-endpoint-function]: https://github.com/chriscalo/goldpage-vue-express-starter/tree/bug-when-logging-this-in-endpoint-function

**Comment by brillout** [comment]
> it blows up with the following error

An edge case led to this unfriendly error to be thrown. It's now fixed in the newly published version `0.5.4`; the proper original error message that explains what's going on is now shown instead. I'm sorry you didn't see the proper error message &mdash; I do care about error messages that contain an explanation.

**Comment by chriscalo** [comment]
Thanks for the fix! 👍 I'll give the a try today

It appears that [Wildcard API is already trying to set `this` when calling the endpoint method by using `endpoint.apply()`][endpoint.apply()]. Any idea why this isn't working? (Is it the use of `Proxy`? Or am I not reading this right?)

``` js
  async function runEndpoint({endpointName, endpointArgs, requestProps, isDirectCall}) {
    // ...
    const endpoint = endpointsObject[endpointName];
    // ...

    const requestProps_proxy = create_requestProps_proxy({requestProps, endpointName, isDirectCall});

    let endpointResult;
    let endpointError;

    try {
      endpointResult = await endpoint.apply(
        requestProps_proxy,
        endpointArgs,
      );
    } catch(err) {
      endpointError = err;
    }

    // ...
  }
```

[endpoint.apply()]: https://github.com/reframejs/wildcard-api/blob/master/server/WildcardApi.js#L356

**Comment by brillout** [comment]
You can read about `bind()` [here](https://github.com/reframejs/wildcard-api/blob/master/docs/ssr-auth.md#readme). It explains why `bind()` is necessary when using the Wildcard client in Node.js.

> Perhaps the more important question: is there somewhere I can put this binding logic once so I don't have to do it on every endpoint call?

I'm afraid not; this is inherent to SSR. You'll always have to manually provide the HTTP request information while doing SSR, no matter whether you use RPC, REST, or GraphQL.

**Comment by chriscalo** [comment]
I now see why the request info must be provided. 👍 Thanks for the explanation.

**Comment by brillout** [comment]
> You'll always have to manually provide the HTTP request information while doing SSR

That said, one thing I want to do is to have Goldpage automatically provide `requestProps` to Wildcard. Although there will be some edge cases where the user will still need to use `bind()`.
