### ISSUE TITLE
Allow custom host/port

### ISSUE THREAD

**Issue by laggingreflex** [reframejs/wildcard-api#17]
Great lib. I was playing around with it for a project. 

I wanted to have the RPC entirely separate into its own service, as opposed to on top of the server that serves the client HTML. 

I also wanted to use [micro](https://github.com/zeit/micro) as the underlying http server. 

I don't suppose this is currently possible? It'd be great if it were, i.e. it allowed the user to specify custom host, port, and path.

**Comment by brillout** [comment]
You can do this, see https://github.com/reframejs/wildcard-api#serverurl

Make sure to update to `wildcard-api@0.6.0`.

> I wanted to have the RPC entirely separate into its own service, as opposed to on top of the server that serves the client HTML.

I'm curious, why?

> Great lib

Thanks

**Comment by laggingreflex** [comment]
Awesome. 

As for why I wanted separate server, it was for a couple use-cases:

* Apps that aren't served by Node, or server-less apps (netlify etc). Even locally, I use webpack-dev-server and a separate API server. 

* I had a [Carlo](https://github.com/GoogleChromeLabs/carlo) app (which has its own [RPC API](https://github.com/GoogleChromeLabs/carlo/blob/master/rpc/rpc.md) but I wanted something else) that doesn't necessarily need a server to host the app. And one that can work remotely. 

I hope I didn't miss something that would've allowed it to be used in these use cases without this change. 

I haven't tested this out yet, I was planning to before commenting but I'll have to put this on the back burner for now. But it looks like this would work, so closing. Thanks for the quick address on the request!

**Comment by brillout** [comment]
Ok I see :+1:
