### ISSUE TITLE
Prebuilt client code served via CDN

### ISSUE THREAD

**Issue by bbarr** [reframejs/wildcard-api#28]
I have just bundled locally and am using that without issue so far, but would love to have an official (and updated) build available for projects that don't use any bundlers.

Edit: Also, fantastic job.. This has felt very clean and really fast to learn!

**Comment by brillout** [comment]
Hi @bbarr 

I'm not shipping a bundled version of `@wildcard-api/client` because I'm assuming that the vast majority of frontend stacks use a bundler nowadays.

So I'm curious; what's your frontend stack?

Would delivering a `@wildcard-api/client` bundle with unpkg solve your problem?

> Edit: Also, fantastic job.. This has felt very clean and really fast to learn!

Thanks, I appreciate your kind words.

**Comment by bbarr** [comment]
Definitely, a UMD bundle or something on unpkg would solve it. If no one else picks this up soon, I can take a shot at a PR.

And most of my projects target modern browsers, so my "stack" has reverted to just HTML, CSS, and JS static files. It's fun, like 2008 again but without IE :)

**Comment by brillout** [comment]
> And most of my projects target modern browsers, so my "stack" has reverted to just HTML, CSS, and JS static files. It's fun, like 2008 again but without IE :)

Sounds fun indeed :-)

Have you heard about Snowpack?

> If no one else picks this up soon, I can take a shot at a PR.

Would love to! I guess we can use a zero-config bundler here such as Parcel. Or Rollup? Your PR would then simply just diff `package.json`.

**Comment by brillout** [comment]
I'm curious; where did you hear about Wildcard?

Thanks for the PR :heart_eyes:
