### ISSUE TITLE
Consider to abandon singleton endpoints instance

### ISSUE THREAD

**Issue by yosbelms** [reframejs/wildcard-api#33]
Currently `endpoints` is a singleton object which gives room for third party libraries to add unwanted edpoints.

You can find more about this [here](https://github.com/yosbelms/remote-func/issues/1)

**Comment by brillout** [comment]
In JavaScript, the source code of all your app's dependencies need to be trusted; any "third party library" has access to your OS which is far worse than knowing about the API.
