### ISSUE TITLE
[Enhancement] Add interceptors  to client and server

### ISSUE THREAD

**Issue by Johnson444** [reframejs/wildcard-api#38]
Hi, It would be cool to have interceptors for client and server similar to axios.

Cheers!

const DEBUG = process.env.NODE_ENV === "development";

```
axios.interceptors.request.use((config) => {
    /** In dev, intercepts request and logs it into console for dev */
    if (DEBUG) { console.info("✉️ ", config); }
    return config;
}, (error) => {
    if (DEBUG) { console.error("✉️ ", error); }
    return Promise.reject(error);
});
```

**Comment by brillout** [comment]
Hi @johnson544 !

You can do this today by wrapping your Wildcard functions:

~~~js
const {endpoints} = require('@wildcard-api/server')

endpoints.getAllTrelloCards = interceptor(function () {
   // SQL/ORM query to get all Trello cards
}, myListener);

endpoints.createTrelloCard = interceptor(function () {
   // SQL/ORM query to create new Trello card
}, myListener);

function myListener({endpointName, endpointArgs, endpointResult, endpointError, context}) {
  const {user} = context;
  if( endpointError ) {
    console.error("✉️ ", 'Wildcard function error', endpointName, endpointArgs, user, endpointError);
  } else {
    console.log("✉️ ", 'New Wildcard call', endpointName, endpointArgs, user);
  }
}

// The machinery
function interceptor(wildcardFunction, callListener) {
  return async function(...endpointArgs) {
    const context = this;

    let endpointResult;
    let endpointError;
    try {
      endpointResult = await wildcardFunction.bind(context)(...endpointArgs);
    } catch(err) {
      endpointError = err;
    }

    // `context._wildcard` doesn't exist today but I can quickly implement it.
    const {endpointName} = context._wildcard;

    callListener({endpointName, endpointArgs, endpointResult, endpointError, context});

    if( endpointError ){
      throw err;
    } else {
      return endpointResult;
    }
  };
}
~~~

Does that work for you?

Although something like following would be more comfy:

~~~js
const {addCallListener} = require('@wildcard-api/server')

addCallListener(myListener);

function myListener({endpointName, endpointArgs, endpointResult, endpointError, context}) {
  const {user} = context;
  if( endpointError ) {
    console.error("✉️ ", 'Wildcard function error', endpointName, endpointArgs, user, endpointError);
  } else {
    console.log("✉️ ", 'new Wildcard call', endpointName, endpointArgs, user);
  }
}
~~~

On the other hand I like Wildcard to be minimalistic; the first solution is all vanilla JavaScript &mdash; kinda cool :-).

The second solution is "easier" though.

A trade off could be to provide the `interceptor` code above as an official helper library e.g. at `@wildcard-api/interceptor`.

Let me know what you think!

**Comment by johnson544** [comment]
Both would work for me. Of course second one is more comfy as you said :-)

Also agree that Wildcard should be slim!

My suggestion would be to add the `context._wildcard` property for now and keep the @wildcard-api/interceptor lib in the backlog

**Comment by brillout** [comment]
Check out [Wildcard Intercept](https://github.com/brillout/wildcard-intercept). It supports `endpointName` ;-).

@lostpebble You may be interested in Wildcard Intercept. (As always feel free to never reply, I know you are busy:).)

> nice side effect: After a few more helper libs we can create an awesome wildcard repo :D :D :D

That'd be lovely indeed!
