### ISSUE TITLE
Sending JSON payload to API in POST body

### ISSUE THREAD

**Issue by lostpebble** [reframejs/wildcard-api#4]
I have noticed that when I call my endpoints, like so:

```typescript
import { endpoints } from "wildcard-api/client";

// in some async function
const response = await endpoints.saveNewCronJob({ newCronJob: editingCronJob });
```

I'm getting a request being sent out that looks like this:

```
http://localhost:8080/wildcard/saveNewCronJob/%5B%7B%22newCronJob%22%3A%7B%22id%22%3A%22%22%2C%22payloadType%22%3A%22TEXT%22%2C%22payload%22%3A%22%22%2C%22title%22%3A%22%22%2C%22timezone%22%3A%22Etc%2FGMT%22%2C%22endpointType%22%3A%22PUBSUB%22%2C%22endpoint%22%3A%22http%3A%2F%2Flocalhost%3A8080%2Ftest-cron-endpoint%22%2C%22enabled%22%3Afalse%2C%22description%22%3A%22%22%2C%22dateUpdated%22%3A%22json-s%3AtYpE%7CDate%7C2019-03-05T14%3A05%3A14.498Z%22%2C%22dateCreated%22%3A%22json-s%3AtYpE%7CDate%7C2019-03-05T14%3A05%3A14.498Z%22%2C%22crontab%22%3A%220%200%201%2F24%20*%20*%20*%22%7D%7D%5D
```

This indicates that the JSON is being serialised and set in the request url as a query string. While this is fine for small payloads, when things get large things might not work out too well (https://stackoverflow.com/questions/32763165/node-js-http-get-url-length-limitation).

**Comment by brillout** [comment]
Good point, I'll fix this.

(The idea of using the URL instead of HTTP payload is to make debugging easier: It's easier to copy paste and modify an URL than to copy paste and modify an HTTP payload.)

I'll make use of HTTP payload for bigger payloads. For smaller payloads I guess we can keep using the URL.

**Comment by lostpebble** [comment]
Okay great. I do get what you mean, but yea maybe do a check on the serialised JSON length, and put it in the POST body if its larger than 200 or so (even that's quite high for a url... might make server logs quite ugly).

**Comment by brillout** [comment]
Have you encountered a problem with Wildcard? Let me know if there is anything that led you away from Wildcard. I'm curious:).

**Comment by brillout** [comment]
Agreed.

Let me know if this is problematic for you and in that case I'll implement this.

**Comment by lostpebble** [comment]
@brillout I think I've hit the limit on this now.

My server is returning:

Status Code: **431** Request Header Fields Too Large

I'm trying to pass relatively large JSON objects to my server. They're actually not even that big, but I think I've hit the limit.

This is the JSON payload I'm sending to the server (prettified):

`
{"id":"wantitall__.__amazon-product-test","scraperEndpoint":{"scrapeFieldSelections":[{"valueName":"priceDollarCents","valueUid":"WNa5uQSShWYZfor","valueFinalType":"integer","valueAttempts":[[{"actionPurpose":"transform","actionEngine":"cheerio","actionArgs":["div[id*=newPitchPriceWrapper] span[class*=priceBlockDealPriceString]"],"actionName":"select","enactTimes":1,"validateArgs":[]},{"actionEngine":"transformer","actionName":"htmlToText","validateArgs":[],"actionArgs":[],"actionPurpose":"transform","enactTimes":1},{"actionEngine":"regex","actionName":"extract","validateArgs":[],"actionArgs":["/\\$(.+)\\.(.+)/"],"actionPurpose":"transform","enactTimes":1},{"actionEngine":"transformer","actionName":"join","validateArgs":[],"actionArgs":[""],"actionPurpose":"transform","enactTimes":1},{"actionEngine":"transformer","actionName":"pickItem","validateArgs":[],"actionArgs":["PICK_FROM_START",0,1],"actionPurpose":"transform","enactTimes":1}],[{"actionPurpose":"transform","actionEngine":"cheerio","actionArgs":["div[id*=newPitchPriceWrapper]"],"actionName":"select","validateArgs":[],"enactTimes":1},{"actionEngine":"transformer","actionName":"htmlToText","validateArgs":[],"actionArgs":[],"actionPurpose":"transform","enactTimes":1},{"actionEngine":"regex","actionName":"extract","validateArgs":[],"actionArgs":["/\\$([^(]+)/"],"actionPurpose":"transform","enactTimes":1},{"actionEngine":"transformer","actionName":"pickItem","validateArgs":[],"actionArgs":["PICK_FROM_START",0,1],"actionPurpose":"transform","enactTimes":2}]],"parentUids":[],"failCondition":"null_or_empty","required":true,"defaultValue":"NULL:"},{"valueName":"shippingWeightPounds","valueUid":"yswmmqQznD5GX7J","valueFinalType":"float","valueAttempts":[[{"actionPurpose":"transform","actionEngine":"cheerio","actionArgs":["li:contains(\"Shipping\")"],"actionName":"select","validateArgs":[],"enactTimes":1},{"actionEngine":"regex","actionName":"extract","validateArgs":[],"actionArgs":["/\\>([^\\>]+)\\spounds.+/"],"actionPurpose":"transform","enactTimes":1},{"actionEngine":"transformer","actionName":"pickItem","validateArgs":[],"actionArgs":["PICK_FROM_START",0,1],"actionPurpose":"transform","enactTimes":2}]],"parentUids":[],"failCondition":"null_or_empty","required":false,"defaultValue":"NULL:"},{"valueName":"shippingWeightOunces","valueUid":"zm-T7Vcl3oBLoVD","valueFinalType":"float","valueAttempts":[[{"actionPurpose":"transform","actionEngine":"cheerio","actionArgs":["tr:contains(\"Shipping Weight\")"],"actionName":"select","validateArgs":[],"enactTimes":1},{"actionEngine":"regex","actionName":"extract","validateArgs":[],"actionArgs":["/([^\\>]+)\\sounces/"],"actionPurpose":"transform","enactTimes":1},{"actionEngine":"transformer","actionName":"pickItem","validateArgs":[],"actionArgs":["PICK_FROM_START",0,1],"actionPurpose":"transform","enactTimes":2}]],"parentUids":[],"failCondition":"null_or_empty","required":false,"defaultValue":"NULL:"},{"valueName":"itemWeightOunces","valueUid":"Ae4YMqUpiT0AXHh","valueFinalType":"string","valueAttempts":[[{"actionPurpose":"transform","actionEngine":"cheerio","actionArgs":["tr:contains(\"Item Weight\")"],"actionName":"select","validateArgs":[],"enactTimes":1},{"actionEngine":"regex","actionName":"extract","validateArgs":[],"actionArgs":["/([^\\>]+)\\sounces/"],"actionPurpose":"transform","enactTimes":1}]],"parentUids":[],"failCondition":"null_or_empty","required":false,"defaultValue":"NULL:"}]},"fields":["scrapeFieldSelections"]}
`

As you can see, its not _that_ long. But probably just long enough to cause the server error response.

As this then becomes the URL:

`http://localhost:5000/wildcard/updateScraperEndpoint/%5B%7B%22id%22%3A%22wantitall__.__amazon-product-test%22%2C%22scraperEndpoint%22%3A%7B%22scrapeFieldSelections%22%3A%5B%7B%22valueName%22%3A%22priceDollarCents%22%2C%22valueUid%22%3A%22WNa5uQSShWYZfor%22%2C%22valueFinalType%22%3A%22integer%22%2C%22valueAttempts%22%3A%5B%5B%7B%22actionPurpose%22%3A%22transform%22%2C%22actionEngine%22%3A%22cheerio%22%2C%22actionArgs%22%3A%5B%22div%5Bid*%3DnewPitchPriceWrapper%5D%20span%5Bclass*%3DpriceBlockDealPriceString%5D%22%5D%2C%22actionName%22%3A%22select%22%2C%22enactTimes%22%3A1%2C%22validateArgs%22%3A%5B%5D%7D%2C%7B%22actionEngine%22%3A%22transformer%22%2C%22actionName%22%3A%22htmlToText%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A1%7D%2C%7B%22actionEngine%22%3A%22regex%22%2C%22actionName%22%3A%22extract%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%22%2F%5C%5C%24(.%2B)%5C%5C.(.%2B)%2F%22%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A1%7D%2C%7B%22actionEngine%22%3A%22transformer%22%2C%22actionName%22%3A%22join%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%22%22%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A1%7D%2C%7B%22actionEngine%22%3A%22transformer%22%2C%22actionName%22%3A%22pickItem%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%22PICK_FROM_START%22%2C0%2C1%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A1%7D%5D%2C%5B%7B%22actionPurpose%22%3A%22transform%22%2C%22actionEngine%22%3A%22cheerio%22%2C%22actionArgs%22%3A%5B%22div%5Bid*%3DnewPitchPriceWrapper%5D%22%5D%2C%22actionName%22%3A%22select%22%2C%22validateArgs%22%3A%5B%5D%2C%22enactTimes%22%3A1%7D%2C%7B%22actionEngine%22%3A%22transformer%22%2C%22actionName%22%3A%22htmlToText%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A1%7D%2C%7B%22actionEngine%22%3A%22regex%22%2C%22actionName%22%3A%22extract%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%22%2F%5C%5C%24(%5B%5E(%5D%2B)%2F%22%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A1%7D%2C%7B%22actionEngine%22%3A%22transformer%22%2C%22actionName%22%3A%22pickItem%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%22PICK_FROM_START%22%2C0%2C1%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A2%7D%5D%5D%2C%22parentUids%22%3A%5B%5D%2C%22failCondition%22%3A%22null_or_empty%22%2C%22required%22%3Atrue%2C%22defaultValue%22%3A%22NULL%3A%22%7D%2C%7B%22valueName%22%3A%22shippingWeightPounds%22%2C%22valueUid%22%3A%22yswmmqQznD5GX7J%22%2C%22valueFinalType%22%3A%22float%22%2C%22valueAttempts%22%3A%5B%5B%7B%22actionPurpose%22%3A%22transform%22%2C%22actionEngine%22%3A%22cheerio%22%2C%22actionArgs%22%3A%5B%22li%3Acontains(%5C%22Shipping%5C%22)%22%5D%2C%22actionName%22%3A%22select%22%2C%22validateArgs%22%3A%5B%5D%2C%22enactTimes%22%3A1%7D%2C%7B%22actionEngine%22%3A%22regex%22%2C%22actionName%22%3A%22extract%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%22%2F%5C%5C%3E(%5B%5E%5C%5C%3E%5D%2B)%5C%5Cspounds.%2B%2F%22%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A1%7D%2C%7B%22actionEngine%22%3A%22transformer%22%2C%22actionName%22%3A%22pickItem%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%22PICK_FROM_START%22%2C0%2C1%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A2%7D%5D%5D%2C%22parentUids%22%3A%5B%5D%2C%22failCondition%22%3A%22null_or_empty%22%2C%22required%22%3Afalse%2C%22defaultValue%22%3A%22NULL%3A%22%7D%2C%7B%22valueName%22%3A%22shippingWeightOunces%22%2C%22valueUid%22%3A%22zm-T7Vcl3oBLoVD%22%2C%22valueFinalType%22%3A%22float%22%2C%22valueAttempts%22%3A%5B%5B%7B%22actionPurpose%22%3A%22transform%22%2C%22actionEngine%22%3A%22cheerio%22%2C%22actionArgs%22%3A%5B%22tr%3Acontains(%5C%22Shipping%20Weight%5C%22)%22%5D%2C%22actionName%22%3A%22select%22%2C%22validateArgs%22%3A%5B%5D%2C%22enactTimes%22%3A1%7D%2C%7B%22actionEngine%22%3A%22regex%22%2C%22actionName%22%3A%22extract%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%22%2F(%5B%5E%5C%5C%3E%5D%2B)%5C%5Csounces%2F%22%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A1%7D%2C%7B%22actionEngine%22%3A%22transformer%22%2C%22actionName%22%3A%22pickItem%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%22PICK_FROM_START%22%2C0%2C1%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A2%7D%5D%5D%2C%22parentUids%22%3A%5B%5D%2C%22failCondition%22%3A%22null_or_empty%22%2C%22required%22%3Afalse%2C%22defaultValue%22%3A%22NULL%3A%22%7D%2C%7B%22valueName%22%3A%22itemWeightOunces%22%2C%22valueUid%22%3A%22Ae4YMqUpiT0AXHh%22%2C%22valueFinalType%22%3A%22string%22%2C%22valueAttempts%22%3A%5B%5B%7B%22actionPurpose%22%3A%22transform%22%2C%22actionEngine%22%3A%22cheerio%22%2C%22actionArgs%22%3A%5B%22tr%3Acontains(%5C%22Item%20Weight%5C%22)%22%5D%2C%22actionName%22%3A%22select%22%2C%22validateArgs%22%3A%5B%5D%2C%22enactTimes%22%3A1%7D%2C%7B%22actionEngine%22%3A%22regex%22%2C%22actionName%22%3A%22extract%22%2C%22validateArgs%22%3A%5B%5D%2C%22actionArgs%22%3A%5B%22%2F(%5B%5E%5C%5C%3E%5D%2B)%5C%5Csounces%2F%22%5D%2C%22actionPurpose%22%3A%22transform%22%2C%22enactTimes%22%3A1%7D%5D%5D%2C%22parentUids%22%3A%5B%5D%2C%22failCondition%22%3A%22null_or_empty%22%2C%22required%22%3Afalse%2C%22defaultValue%22%3A%22NULL%3A%22%7D%5D%7D%2C%22fields%22%3A%5B%22scrapeFieldSelections%22%5D%7D%5D`

I'm confirming that its the length of the JSON payload causing the error by slightly reducing the amount of data sent in my interface (remove some fields) - and it then works no problem.

**Comment by brillout** [comment]
I will fix this today or tomorrow. If this is urgent on your side, let me know.

**Comment by lostpebble** [comment]
I've replaced that endpoint with a custom API of my own which is working fine for now.

**Comment by brillout** [comment]
(I didn't forget about this. I'm on vacation. Ttyl.)

**Comment by brillout** [comment]
@lostpebble Done. Sorry for the delay. Re-open this if you encounter any issue. Update Wildcard to `wildcard-api@0.5.0` Note that, from now on, you will have to provide the HTTP request body to `getApiResponse`:

~~~js
const express = require('express');
const {getApiResponse} = require('wildcard-api'); // npm install wildcard-api

const app = express();
app.use(express.json()); // Make sure to parse the HTTP request body

app.all('/wildcard/*' , async (req, res) => {
  const requestProps = {
    url: req.url,
    method: req.method,
    // Make srue to pass down `body`.
    body: req.body,
  };
  const responseProps = await getApiResponse(requestProps);
  res.status(responseProps.statusCode);
  // Warning: this is now named `contentType`:
  res.type(responseProps.contentType);
  res.send(responseProps.body);
~~~

Also note that I renamed `responseProps.content` to `responseProps.contentType`.

For other server frameworks: https://github.com/reframejs/wildcard-api#getting-started

**Comment by lostpebble** [comment]
Thanks @brillout ! No worries about the delay, managed with a temporary fix until now (was just a single endpoint for now). Will update the package and try out the new way soon.

**Comment by lostpebble** [comment]
Hi @brillout !

Was just wondering. Is there any way to force Wildcard to always use `POST` with a `JSON` Request payload, instead of how it now does it with encoding everything into the URL?

I actually find this harder to debug because all my JSON is scrambled into the URL instead of nicely presented in Chrome Dev Tools under "Request Payload".

I also prefer for my server logs to be cleaner, as now they are filled with super long, basically unreadable, URLs.

**Comment by brillout** [comment]
Hey Paul,

Makes sense! I will implement this tentatively today, latest in the next couple of days.

Romuald

**Comment by brillout** [comment]
Done & published in `wildcard-api@0.5.3`. Docs at https://github.com/reframejs/wildcard-api#options.

**Comment by lostpebble** [comment]
Great, thanks for the speedy implementation!

**Comment by brillout** [comment]
Hi @lostpebble, I just published a breaking change about this: https://github.com/reframejs/wildcard-api/releases/tag/v0.6.0

**Comment by brillout** [comment]
@lostpebble I actually realized that the old interface was more convenient. I just published a new major version `v0.7.x` that is backwards compatible with `v0.5.x`. So if you update Wildcard from `v0.5.x` to `v0.7.x` you can keep your code as it is.

**Comment by lostpebble** [comment]
Okay cool, thanks. Will check it out soon.

**Comment by brillout** [comment]
There is nothing to check out :) Just update to `v0.7.x` and leave your code as it is. (Or simply keep `v0.5.x`.)
