### ISSUE TITLE
Cannot find type declarations with typescript

### ISSUE THREAD

**Issue by michie1** [reframejs/wildcard-api#49]
I try to use wildcard-api with typescript and `tsc` is erroring on a missing type declaration.

`import wildcard from "@wildcard-api/server/express";`

`Cannot find module '@wildcard-api/server/express' or its corresponding type declarations.`

Any ideas where I can find the types?

**Comment by brillout** [comment]
Hi @michie1 

Wildcard doesn't have type declaration; would using `any` be ok for you?

You can however type your endpoint functions, as described in https://github.com/reframejs/wildcard-api#typescript

**Comment by michie1** [comment]
Hello @brillout. 

Thank you for the answer. I just wasn't sure I did something wrong or if they weren't there.
I've created a file `index.d.ts` with

```
declare module "@wildcard-api/server";
declare module "@wildcard-api/server/express";
declare module "@wildcard-api/client";
```
in order to resolve the errors and that yields `any`s.

Sharing the types of the endpoints works wonderful. You can close this issue if you want.

**Comment by brillout** [comment]
:+1: Let me know if there is anything else.

Rom
