### ISSUE TITLE
Namespaced endpoints?

### ISSUE THREAD

**Issue by gamedevsam** [reframejs/wildcard-api#55]
Can you have namespaced endpoints with wildcard?

For example:

```
endpoints.users.create = async function() {...}
endpoints.posts.create = async function() {...}
```

I know this is a bit semantics since you could have a `createUser` and `createPost` endpoints, but as the API surface grows being able to have namespaced routes becomes a valuable tool.

**Comment by brillout** [comment]
Closing this but if someone wants this let me know. I'm open to implement what Samuel said:

> I imagine adding this type of functionality would not be too difficult if someone really wanted it since endpoints is just a proxy which could be modified to handle objects with function keys as well as simple functions.
