### ISSUE TITLE
Wilcard current status 

### ISSUE THREAD

**Issue by cloudcompute** [reframejs/wildcard-api#67]
Hi

I have a few questions. Would you pl. reply?

a. Wildcard is not maintained any longer. Can we still use it in production?

b. This package is not published on npm. Any specific reason?

c. There is a wildcard equivalent, namely, trpc. Here is the link: https://github.com/trpc/trpc/ 
Could you pl. give your opinion what shall we we use? I am looking forward to use Fastify in the backend and React SSR on frontend.

Thanks

**Comment by brillout** [comment]
Use [Telefunc](https://telefunc.com/).

**Comment by ramandhingra** [comment]
Is telefunc production ready? Could you pl. tell what makes it superior than others?

**Comment by ramandhingra** [comment]
Thank you so much for offering the support like a professional within 24 hours for an open source project.

a. I do not want to use Zod to define the telefunction arguments. I am simply looking for validations like date, number: min-max, sting matching, regular expression matching for strong passwords, a value must be one among the following types.. enum

i. Not only zod, the developer should be able to use any validation library like yup, joi, superstruct etc.
ii. Shared validation is an ideal solution. For example, create a file named validations.ts inside the shared folder. At client side, invoke these validations before we update a db. At client side, access this same set of validations before we submit a form to the server.

Here is a detailed list of different types of validations.. see its Readme.md file.. https://github.com/jquense/yup

b. SuperJSON allows us to able to transparently use e.g. standard Date/Map/Sets over the wire between the server and client. Can we use something like SuperJSON in telefunc?

Some suggestions:
a. The following methods like register(), login() don't need to be prtoected while all other, let's say, 100 API routes need to be. Placing the Abort code inside the 100 methods is tedious.

Instead, use decorators just like NestJS does
@IsAuthenticated()
@IsRole("Admin")
async listUSers (...)

b. The usage of shield looks a bit ambiguous. 100 RPC methods resulting in 100 shields. 

shield(onCommentDelete, [shield.type.number])
export async function onCommentDelete(id) { ... }

Here the function name is duplicated. If 5 arguments, shield.type.xxx will occur 5 times. Also, a parameter type is missing in the function's signatures, readability suffers.

Probably, intead of shield, just use a decorator named RPC indicating that it can be accessed from the client side. 
@RPC
const onCommentDelete = (id: number): boolean => { ... }

The telefunc should be able to infer the parameter and return types from within the method defintion itself. No need of shield in this case.

Last but not the least, I really don't know whether all this stuff like Context, Authentication, Permission, Abort really required. According to me, let the developer handle all this  itself.  If Telefunc still wants to provide support for Context, Abort, etc. good enough. But it should be optional, let him use whatever libraries and framework features he wants to use for Error Handling, Validation, making the Context available to RPC methods, etc.

Loking forward to hear from you.

Thanks

**Comment by ramandhingra** [comment]
Thank you so much for offering the support like a professional within 24 hours for an open source project.

a. I do not want to use Zod to define the telefunction arguments. I am simply looking for validations like date, number: min-max, sting matching, regular expression matching for strong passwords, a value must be one among the following types.. enum

i. Not only zod, the developer should be able to use any validation library like yup, joi, superstruct etc.
ii. Shared validation is an ideal solution. For example, create a file named validations.ts inside the shared folder. At client side, invoke these validations before we update a db. At client side, access this same set of validations before we submit a form to the server.

Here is a detailed list of different types of validations.. see its Readme.md file.. https://github.com/jquense/yup

b. SuperJSON allows us to able to transparently use e.g. standard Date/Map/Sets over the wire between the server and client. Can we use something like SuperJSON in telefunc?

Some suggestions:
a. The following methods like register(), login() don't need to be prtoected while all other, let's say, 100 API routes need to be. Placing the Abort code inside the 100 methods is tedious.

Instead, use decorators just like NestJS does

```
@IsAuthenticated()
@IsRole("Admin")
async listUSers (...)
```

b. The usage of shield is monotonous. 100 RPC methods resulting in 100 shields. 

```
shield(onCommentDelete, [shield.type.number])
export async function onCommentDelete(id) { ... }
```

Here the function name is duplicated. If 5 arguments, shield.type.xxx will occur 5 times. Also, a parameter type is missing in the function's signatures, readability suffers.

Probably, intead of shield, just use a decorator named RPC indicating that it can be accessed from the client side. 
```
@RPC
const onCommentDelete = (id: number): boolean => { ... }
```

The telefunc should be able to infer the parameter and return types from within the method definition itself. No need of shield in this case.

Last but not the least, I really don't know whether all this stuff like Context, Authentication, Permission, Abort is really required. According to me, let the developer handle all this  by himself.  If telefunc still wants to provide support for Context, Abort, etc. good enough. But it should be optional, let him use whatever libraries and framework features he wants to use for Error Handling, Validation, making the Context available to RPC methods, etc.

To infer the types, this package might be of help to you:
https://www.npmjs.com/package/reflect-metadata



Looking forward to hear from you.

Thanks

**Comment by ramandhingra** [comment]
This syntax is better than the previous one. I'll read the documentation.

Thanks

**Comment by brillout** [comment]
Feel free to further ask questions after you're more familiar with Telefunc's way of doing things.

**Comment by brillout** [comment]
> There is no reliable way to infer TS types at runtime, and reflect-metadata won't change that.

Actually, we could make it work.

I'm working on other things right now, but if you'd be up to contribute we can start implementing it.

**Comment by cloudcompute** [comment]
I could not get back to you earlier. For now, I decided not to use the RPC in my current project. I am sorry I won't be able to devote time as I quite busy with the new project.

This [link](https://github.com/qiwi/json-rpc/blob/fbd5890edebd7d511743490b48c2109bd9d409f3/packages/p3/src/main/ts/common/decorators/class.ts) may give you some leads if you want to implement it.
